### ISSUE TITLE
Space in your LinkedIn URL

### ISSUE THREAD

**Issue by mflr0** [MrChausson/MrChausson#1]
There is a space between the first name Clément and the last name Chausson, which causes the LinkedIn button to be broken
I hope it won't be too hard to fix :p
<img width="411" alt="Screenshot 2022-10-07 at 15 46 04" src="https://user-images.githubusercontent.com/72016897/194568486-ca9c281f-4f73-495e-8c94-ab8d159b6c4d.png">

**Comment by MrChausson** [comment]
Thanks for the heads-up, it is fixed now ;)
